### ISSUE TITLE
Sprint #1: GIF walkthrough

### ISSUE THREAD

**Issue by XiangliDai** [the-town-kitchen/the-town-kitchen#11]
![the-town-kitchen](https://cloud.githubusercontent.com/assets/643304/6610539/f0761314-c81d-11e4-9cbf-e9083b069feb.gif)
/cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: Nice work creating wire-frames and creating stories for sprint 1. Great to see the basic screens and flow coming along well. Few notes to mention:
- Well defined tasks (issues) and properly assigned to team members.
- Group projects can reinforce skills that are relevant to both group and individual work including the ability to plan and manage time. For this reason, it is imperative that you [group all detailed issues into milestones](https://github.com/the-town-kitchen/the-town-kitchen/milestones) representing sprints so that its easier for you to track progress of the project.
- Consider creating group [milestones/pull requests](https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/) to better track your progress and review each others code.
- Good to see each member of the team [contributing](https://github.com/the-town-kitchen/the-town-kitchen/graphs/contributors) to the project.
- Depending on the strategy your group has come up with, consider creating regular pushes/pull-requests to sync up your code to avoid having multiple errors at the end.
- Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Good to see the basic flow coming along well. Please take notes of these points and improve upon the same in the next sprint. Look forward to the rest of the functionality and improvement on the core flows by the end of the Sprint 2 so you can have enough time to add UI polish and advanced nice-to-have features later on.  It is those little extra things you do that make everything feel more polished and desirable to use.
