### ISSUE TITLE
[Android Bootcamp] Group Project: Sprint 2

### ISSUE THREAD

**Issue by MarinaMurashev** [the-town-kitchen/the-town-kitchen#28]
Our app is complete, please review. /cc @codepathreview @codepath @XiangliDai @paulinar

![the-town-kitchen](https://cloud.githubusercontent.com/assets/2048138/7787089/b229cff6-01ac-11e5-9094-e80995f2ae63.gif)

note, there's a part in the gif where it looks like nothing is happening on the MealListActivity, and that's where I'm just changing a status in parse, so there is more to the gif where we relaunch the app.

**Comment by codepathreview** [comment]
:+1: Great work so far on the group project. Your team has made great progress in the last week. Hope you are proud of what you have achieved in ~6 weeks.
- Good job on achieving your sprint 2 milestone. Glad to see you created and assigned tasks to everyone so that everyone has equal opportunity to learn.
- Good work implementing the core flows. You guys have made great progress in sprint 2 and it seems like most of your application logic is in place.
- Try to challenge yourself on the UI/visual side of things in the coming days. Not necessarily flashy things, but it's the small details that take a lot of work.
- Keep working on integrating the core flows/nice to have features and make sure all pieces fit together perfectly.
- Consult with your mentors to get their feedback as often as you can. Remember they are here to help!
- While working on polishing your app for next sprint, remember that your app follows the [android design guidelines](http://guides.codepath.com/android/Android-Design-Guidelines) and also benchmark your app on sites such as [android app patterns](http://www.android-app-patterns.com/) to improve the UI/UX.

Take time this week to clean up and polish your app. Generally, most of these tasks are small and easy, but go a long way in making an impact on how your app will get perceived. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most appealing story that gains the most attention on the demo day. Excited to see your progress next week!
